version: "3.5"

x-common: &common
  restart: unless-stopped
  networks:
    - indexer_network

x-anton-rewrites: &anton-rewrites
  build: .
  image: "${IMAGE_NAME:-anton}:${IMAGE_TAG:-latest}"

services:

  redpanda:
    <<: *common
    image: docker.redpanda.com/redpandadata/redpanda:latest
    ports:
      - '9092:9092'
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
  console:
    <<: *common
    image: docker.redpanda.com/redpandadata/console:latest
    entrypoint: /bin/sh
    ports:
      - '8085:8080'
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        connect:
          enabled: true
          clusters:
            - name: datagen
              url: http://connect:8083
  
  

  indexer:
    <<: *anton-rewrites
  web:
    <<: *anton-rewrites
  migrations:
    <<: *anton-rewrites
  clickhouse:
    ports:
      - "9000:9000"
      - "8123:8123"
  postgres:
    ports:
      - "5432:5432"
